### ISSUE TITLE
Doc and src packages for 1.3.2 not found in repo1.maven.org

### ISSUE THREAD

**Issue by aleksandr-vin** [sbt/sbt-native-packager#1063]
I'm migrating my project from 2.11 to 2.12, almost everything is done, but docs and src jars for that package are missed.

```
$ sbt updateSbtClassifiers
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/aleksandrvin/Developer/hogr/hogr-cms/project
[info] Loading settings from build.sbt ...
[info] Set current project to hogr-cms (in build file:/Users/aleksandrvin/Developer/hogr/hogr-cms/)
[warn] 	Detected merged artifact: [FAILED     ] com.typesafe.sbt#sbt-native-packager;1.3.2!sbt-native-packager.jar(src):  (0ms).
[warn] ==== local: tried
[warn]   /Users/aleksandrvin/.ivy2/local/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.3.2/srcs/sbt-native-packager-sources.jar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.3.2/sbt-native-packager-1.3.2-sources.jar
[warn] ==== local-preloaded-ivy: tried
[warn] ==== local-preloaded: tried
[warn]   file:////Users/aleksandrvin/.sbt/preloaded/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.3.2/sbt-native-packager-1.3.2-sources.jar
[warn] 	Detected merged artifact: [FAILED     ] com.typesafe.sbt#sbt-native-packager;1.3.2!sbt-native-packager.jar(doc):  (0ms).
[warn] ==== local: tried
[warn]   /Users/aleksandrvin/.ivy2/local/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.3.2/docs/sbt-native-packager-javadoc.jar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.3.2/sbt-native-packager-1.3.2-javadoc.jar
[warn] ==== local-preloaded-ivy: tried
[warn] ==== local-preloaded: tried
[warn] 	Detected merged artifact: [FAILED     ] com.typesafe.sbt#sbt-web;1.4.3!sbt-web.jar(doc):  (0ms).
[warn] ==== local: tried
[warn]   /Users/aleksandrvin/.ivy2/local/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.3/docs/sbt-web-javadoc.jar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-web_2.12_1.0/1.4.3/sbt-web-1.4.3-javadoc.jar
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/aleksandrvin/.sbt/preloaded/com.typesafe.sbt/sbt-web/1.4.3/docs/sbt-web-javadoc.jar
[warn] ==== local-preloaded: tried
[warn]   file:////Users/aleksandrvin/.sbt/preloaded/com/typesafe/sbt/sbt-web_2.12_1.0/1.4.3/sbt-web-1.4.3-javadoc.jar
[warn] 	Detected merged artifact: [FAILED     ] com.typesafe.sbt#sbt-web;1.4.3!sbt-web.jar(src):  (0ms).
[warn] ==== local: tried
[warn]   /Users/aleksandrvin/.ivy2/local/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.3/srcs/sbt-web-sources.jar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-web_2.12_1.0/1.4.3/sbt-web-1.4.3-sources.jar
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/aleksandrvin/.sbt/preloaded/com.typesafe.sbt/sbt-web/1.4.3/srcs/sbt-web-sources.jar
[warn] ==== local-preloaded: tried
[warn]   file:////Users/aleksandrvin/.sbt/preloaded/com/typesafe/sbt/sbt-web_2.12_1.0/1.4.3/sbt-web-1.4.3-sources.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.sbt#sbt-web;1.4.3!sbt-web.jar(doc)
[warn] 	:: com.typesafe.sbt#sbt-web;1.4.3!sbt-web.jar(src)
[warn] 	:: com.typesafe.sbt#sbt-native-packager;1.3.2!sbt-native-packager.jar(src)
[warn] 	:: com.typesafe.sbt#sbt-native-packager;1.3.2!sbt-native-packager.jar(doc)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[error] sbt.librarymanagement.ResolveException: download failed: com.typesafe.sbt#sbt-web;1.4.3!sbt-web.jar(doc)
[error] download failed: com.typesafe.sbt#sbt-web;1.4.3!sbt-web.jar(src)
[error] download failed: com.typesafe.sbt#sbt-native-packager;1.3.2!sbt-native-packager.jar(src)
[error] download failed: com.typesafe.sbt#sbt-native-packager;1.3.2!sbt-native-packager.jar(doc)
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.transitiveScratch(LibraryManagement.scala:135)
[error] 	at sbt.Classpaths$.$anonfun$sbtClassifiersTasks$12(Defaults.scala:2175)
[error] 	at sbt.Classpaths$$anon$4.call(Defaults.scala:2253)
[error] 	at sbt.Classpaths$$anon$4.call(Defaults.scala:2246)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.Classpaths$.withExcludes(Defaults.scala:2246)
[error] 	at sbt.Classpaths$.$anonfun$sbtClassifiersTasks$10(Defaults.scala:2162)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[INFO] [11/05/2017 11:33:59.158] [Thread-8] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
[error] (*:updateSbtClassifiers) sbt.librarymanagement.ResolveException: download failed: com.typesafe.sbt#sbt-web;1.4.3!sbt-web.jar(doc)
[error] download failed: com.typesafe.sbt#sbt-web;1.4.3!sbt-web.jar(src)
[error] download failed: com.typesafe.sbt#sbt-native-packager;1.3.2!sbt-native-packager.jar(src)
[error] download failed: com.typesafe.sbt#sbt-native-packager;1.3.2!sbt-native-packager.jar(doc)
[error] Total time: 11 s, completed Nov 5, 2017 11:33:59 AM
$
```

```
$ cat project/build.properties
#Activator-generated Properties
#Tue Oct 04 16:51:07 CDT 2016
template.uuid=16e5b0de-d1aa-4ccf-9350-ffdc3995e26a
sbt.version=1.0.3
$ cat project/plugins.sbt
// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.7")

// web plugins

//addSbtPlugin("com.typesafe.sbt" % "sbt-coffeescript" % "1.0.0")
//addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.1.0")
//addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.4")
//addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.8")
//addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.1.1")
//addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.1.0")
//addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.6")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.9.3")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.7.0")
```

```
$ cat build.sbt
name := """hogr-cms"""

//
// See http://blog.byjean.eu/2015/07/10/painless-release-with-sbt.html
//

lazy val root = (project in file(".")).
  enablePlugins(PlayScala, DebianPlugin, SystemdPlugin, BuildInfoPlugin, GitVersioning, GitBranchPrompt).
  settings(
    buildInfoKeys := Seq[BuildInfoKey](name, version, scalaVersion, sbtVersion),
    buildInfoPackage := "co.aleksandrvin.hogrcms.buildinfo"
  )

git.useGitDescribe := true
git.baseVersion := "1.0.0"
val VersionRegex = "v([0-9]+.[0-9]+.[0-9]+)-?(.*)?".r
git.gitTagToVersionNumber := {
  case VersionRegex(v,"") => Some(v)
  case VersionRegex(v,"SNAPSHOT") => Some(s"$v-SNAPSHOT")
  case VersionRegex(v,s) => Some(s"$v-$s-SNAPSHOT")
  case _ => None
}

buildInfoOptions += BuildInfoOption.ToJson
buildInfoOptions += BuildInfoOption.BuildTime

maintainer in Linux := "aleksandrvin"
packageSummary in Linux := "HOGR CMS"
packageDescription := "HOGR"

scalaVersion := "2.12.4"

libraryDependencies ++= Seq(
  "com.typesafe.play" %% "play-slick" % "3.0.2",
  "com.typesafe.play" %% "play-slick-evolutions" % "3.0.2",
  "com.typesafe.play" %% "play-json" % "2.6.7",
  "org.xerial" % "sqlite-jdbc" % "3.16.1",
  "org.postgresql" % "postgresql" % "9.4.1212",
  "org.picoworks" %% "pico-hashids"  % "4.4.141",
  "com.github.tototoshi" %% "slick-joda-mapper" % "2.3.0",
  specs2 % Test,
  "org.scalatestplus.play" %% "scalatestplus-play" % "3.1.2" % "test",
  "org.scalamock" %% "scalamock-scalatest-support" % "3.6.0" % "test",
  "net.kaliber" %% "play-s3" % "9.0.0",
  ws
)
libraryDependencies += scalaVersion("org.scala-lang" % "scala-compiler" % _).value

libraryDependencies += filters

javaOptions in Universal ++= Seq(
  // JVM memory tuning
  "-J-Xmx1024m",
  "-J-Xms512m",

  // Since play uses separate pidfile we have to provide it with a proper path
  // name of the pid file must be play.pid
  s"-Dpidfile.path=/var/run/${packageName.value}/play.pid",

  // alternative, you can remove the PID file
  s"-Dpidfile.path=/dev/null",

  s"-Dconfig.resource=production.conf"

  // Use separate configuration file for production environment
  //s"-Dconfig.file=/usr/share/${packageName.value}/conf/production.conf",

  // Use separate logger configuration file for production environment
  //s"-Dlogger.file=/usr/share/${packageName.value}/conf/logback.xml"
)
```

```
$ uname -a
Darwin Aleksandrs-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
$
```

**Comment by aleksandr-vin** [comment]
Was able to workaround it for me by publishing locally the project

**Comment by calvinlfer** [comment]
You need the following resolver for this work:
```sbt
resolvers += Resolver.sbtPluginRepo("releases")
```

This should be documented in the installation section

**Comment by muuki88** [comment]
SBT adds these by default. Only if you remove the predefined one's, you need to readd them. Or am I missing something?

**Comment by dwickern** [comment]
It's failing to download sources and docs, not the main artifact. I saw this problem too (and not specific to sbt-native-packager) when I tried to upgrade to sbt 1.0

My workaround was
```sbt
updateConfiguration in updateSbtClassifiers := (updateConfiguration in updateSbtClassifiers).value.withMissingOk(true)
```

Looks like sbt/sbt#3432 is the root issue

**Comment by aleksandr-vin** [comment]
@dwickern looks valid, closing this issue here

**Comment by muuki88** [comment]
Thanks @dwickern for taking care of this <3
