### ISSUE TITLE
Documentation for specific version not published anymore

### ISSUE THREAD

**Issue by marcospereira** [sbt/sbt-native-packager#1087]
## Expected behaviour

I can navigate and link the docs for a specific version, for example:

http://sbt-native-packager.readthedocs.io/en/v1.3.2/

## Actual behaviour

Only `/latest/` and `/stable` are accessible, but there are links to versions' docs at the bottom left of the page.

Not sure if this is intentional, but this generates dead links in PlayFramework documentation (see https://github.com/playframework/playframework/pull/8130).

**Comment by muuki88** [comment]
Thanks for your report. There seems to be an issue with readthedocs.org
The master builds correctly, but the version tag failed with

```
python2.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2
python /home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/bin/pip install --use-wheel --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/.cache/pip Pygments==2.2.0 setuptools<40 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.6.5 sphinx-rtd-theme<0.3 readthedocs-sphinx-ext<0.6
cat src/sphinx/conf.py
python /home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.6.5
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 28 source files that are out of date
updating environment: 28 added, 0 changed, 0 removed
reading sources... [  3%] archetypes/cheatsheet
reading sources... [  7%] archetypes/index
reading sources... [ 10%] archetypes/java_app/customize
reading sources... [ 14%] archetypes/java_app/index
reading sources... [ 17%] archetypes/java_server/customize
reading sources... [ 21%] archetypes/java_server/index
reading sources... [ 25%] archetypes/misc_archetypes
reading sources... [ 28%] archetypes/systemloaders
reading sources... [ 32%] formats/debian
reading sources... [ 35%] formats/docker
reading sources... [ 39%] formats/index
reading sources... [ 42%] formats/jdkpackager
reading sources... [ 46%] formats/linux
reading sources... [ 50%] formats/rpm
reading sources... [ 53%] formats/universal
reading sources... [ 57%] formats/windows
reading sources... [ 60%] gettingstarted
reading sources... [ 64%] index
reading sources... [ 67%] introduction
reading sources... [ 71%] recipes/custom
reading sources... [ 75%] recipes/deployment
reading sources... [ 78%] recipes/embedded-jvm
reading sources... [ 82%] recipes/index
reading sources... [ 85%] recipes/longclasspath
reading sources... [ 89%] recipes/package_configuration
reading sources... [ 92%] recipes/play
reading sources... [ 96%] recipes/scalajs
reading sources... [100%] recipes/umask

/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/checkouts/v1.3.2/src/sphinx/archetypes/java_server/customize.rst:123: WARNING: Inline literal start-string without end-string.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... /home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/checkouts/v1.3.2/src/sphinx/recipes/umask.rst: WARNING: document isn't included in any toctree
done
writing output... [  3%] archetypes/cheatsheet
writing output... [  7%] archetypes/index
writing output... [ 10%] archetypes/java_app/customize
writing output... [ 14%] archetypes/java_app/index
writing output... [ 17%] archetypes/java_server/customize
writing output... [ 21%] archetypes/java_server/index
writing output... [ 25%] archetypes/misc_archetypes
writing output... [ 28%] archetypes/systemloaders
writing output... [ 32%] formats/debian
writing output... [ 35%] formats/docker
writing output... [ 39%] formats/index
writing output... [ 42%] formats/jdkpackager
writing output... [ 46%] formats/linux
writing output... [ 50%] formats/rpm
/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/checkouts/v1.3.2/src/sphinx/archetypes/java_server/customize.rst:7: WARNING: unknown document: my-first-project

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 397, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 434, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 443, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 561, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 954, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/readthedocs_ext/readthedocs.py", line 100, in rtd_render
    content = old_render(template, render_context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/jinja2glue.py", line 176, in render
    return self.environment.get_template(template).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx_rtd_theme/layout.html", line 127, in top-level template code
    {% block menu %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx_rtd_theme/layout.html", line 133, in block "menu"
    {% set global_toc = toctree(maxdepth=theme_navigation_depth|int, collapse=theme_collapse_navigation, includehidden=True) %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/jinja2/sandbox.py", line 427, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 943, in <lambda>
    ctx['toctree'] = lambda **kw: self._get_local_toctree(pagename, **kw)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 856, in _get_local_toctree
    docname, self, collapse, **kwds))['fragment']
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/environment/adapters/toctree.py", line 309, in get_toctree_for
    doctree = self.env.get_doctree(self.env.config.master_doc)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 895, in get_doctree
    with open(doctree_filename, 'rb') as f:
IOError: [Errno 2] No such file or directory: u'/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/checkouts/v1.3.2/src/sphinx/_build/doctrees-readthedocs/index.doctree'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/envs/v1.3.2/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 895, in get_doctree
    with open(doctree_filename, 'rb') as f:
IOError: [Errno 2] No such file or directory: u'/home/docs/checkouts/readthedocs.org/user_builds/sbt-native-packager/checkouts/v1.3.2/src/sphinx/_build/doctrees-readthedocs/index.doctree'
The full traceback has been saved in /tmp/sphinx-err-tsZw9i.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Wiping and rebuilding didn't help.

**Comment by muuki88** [comment]
It seems that there was an issue with readthedocs. Build no worked and is online :)

**Comment by marcospereira** [comment]
Thank you, @muuki88!

**Comment by mkurz** [comment]
Same problem again? No docs for 1.3.18 published yet.
