### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1 when running sbt elastic-beanstalk:dist

### ISSUE THREAD

**Issue by yFotouh** [sbt/sbt-native-packager#1098]
I was trying to deploy a java play framework application with this code :

https://github.com/kipsigman/play-elastic-beanstalk
However , when i reach this step 

`sbt elastic-beanstalk:dist`

i get this following errors:

```
[debug]         [NOT REQUIRED] com.typesafe.play#play-functional_2.11;2.5.3!play
-functional_2.11.jar
[debug]         [NOT REQUIRED] com.typesafe.play#play-datacommons_2.11;2.5.3!pla
y-datacommons_2.11.jar
[debug]         [NOT REQUIRED] org.reactivestreams#reactive-streams;1.0.0!reacti
ve-streams.jar
[debug]         [NOT REQUIRED] com.typesafe.akka#akka-stream_2.11;2.4.4!akka-str
eam_2.11.jar
[debug]         [NOT REQUIRED] com.typesafe#ssl-config-akka_2.11;0.2.1!ssl-confi
g-akka_2.11.jar(bundle)
[debug]         [NOT REQUIRED] com.typesafe#ssl-config-core_2.11;0.2.1!ssl-confi
g-core_2.11.jar(bundle)
[debug]         [NOT REQUIRED] xml-apis#xml-apis;1.4.01!xml-apis.jar
[debug]         [NOT REQUIRED] javax.inject#javax.inject;1!javax.inject.jar
[debug]         [NOT REQUIRED] aopalliance#aopalliance;1.0!aopalliance.jar
[debug]         [NOT REQUIRED] com.google.guava#guava;16.0.1!guava.jar(bundle)
[debug]         [NOT REQUIRED] com.typesafe.netty#netty-reactive-streams-http;1.
0.5!netty-reactive-streams-http.jar
[debug]         [NOT REQUIRED] io.netty#netty-transport-native-epoll;4.0.36.Fina
l!netty-transport-native-epoll.jar
[debug]         [NOT REQUIRED] com.typesafe.netty#netty-reactive-streams;1.0.5!n
etty-reactive-streams.jar
[debug]         [NOT REQUIRED] io.netty#netty-codec-http;4.0.34.Final!netty-code
c-http.jar
[debug]         [NOT REQUIRED] io.netty#netty-handler;4.0.34.Final!netty-handler
.jar
[debug]         [NOT REQUIRED] io.netty#netty-codec;4.0.34.Final!netty-codec.jar

[debug]         [NOT REQUIRED] io.netty#netty-common;4.0.36.Final!netty-common.j
ar
[debug]         [NOT REQUIRED] io.netty#netty-buffer;4.0.36.Final!netty-buffer.j
ar
[debug]         [NOT REQUIRED] io.netty#netty-transport;4.0.36.Final!netty-trans
port.jar
[debug]         [NOT REQUIRED] ch.qos.logback#logback-core;1.1.4!logback-core.ja
r
[debug]         [NOT REQUIRED] ch.qos.logback#logback-classic;1.1.4!logback-clas
sic.jar
[debug]         [NOT REQUIRED] com.typesafe.play#play-test_2.11;2.5.3!play-test_
2.11.jar
[debug]         [NOT REQUIRED] org.scalatestplus.play#scalatestplus-play_2.11;1.
5.1!scalatestplus-play_2.11.jar
[debug]         [NOT REQUIRED] junit#junit;4.12!junit.jar
[debug]         [NOT REQUIRED] com.novocode#junit-interface;0.11!junit-interface
.jar
[debug]         [NOT REQUIRED] com.google.guava#guava;19.0!guava.jar(bundle)
[debug]         [NOT REQUIRED] com.google.code.findbugs#jsr305;3.0.1!jsr305.jar
[debug]         [NOT REQUIRED] net.sourceforge.htmlunit#htmlunit;2.20!htmlunit.j
ar
[debug]         [NOT REQUIRED] org.fluentlenium#fluentlenium-core;0.10.9!fluentl
enium-core.jar
[debug]         [NOT REQUIRED] org.hamcrest#hamcrest-core;1.3!hamcrest-core.jar
[debug]         [NOT REQUIRED] org.scala-sbt#test-interface;1.0!test-interface.j
ar
[debug]         [NOT REQUIRED] xalan#xalan;2.7.2!xalan.jar
[debug]         [NOT REQUIRED] org.apache.httpcomponents#httpclient;4.5.2!httpcl
ient.jar
[debug]         [NOT REQUIRED] org.apache.httpcomponents#httpmime;4.5.2!httpmime
.jar
[debug]         [NOT REQUIRED] net.sourceforge.htmlunit#htmlunit-core-js;2.17!ht
mlunit-core-js.jar
[debug]         [NOT REQUIRED] net.sourceforge.nekohtml#nekohtml;1.9.22!nekohtml
.jar
[debug]         [NOT REQUIRED] net.sourceforge.cssparser#cssparser;0.9.18!csspar
ser.jar
[debug]         [NOT REQUIRED] commons-io#commons-io;2.4!commons-io.jar
[debug]         [NOT REQUIRED] commons-logging#commons-logging;1.2!commons-loggi
ng.jar
[debug]         [NOT REQUIRED] org.eclipse.jetty.websocket#websocket-client;9.2.
15.v20160210!websocket-client.jar
[debug]         [NOT REQUIRED] xalan#serializer;2.7.2!serializer.jar
[debug]         [NOT REQUIRED] org.apache.httpcomponents#httpcore;4.4.4!httpcore
.jar
[debug]         [NOT REQUIRED] org.w3c.css#sac;1.3!sac.jar
[debug]         [NOT REQUIRED] org.eclipse.jetty#jetty-util;9.2.15.v20160210!jet
ty-util.jar
[debug]         [NOT REQUIRED] org.eclipse.jetty#jetty-io;9.2.15.v20160210!jetty
-io.jar
[debug]         [NOT REQUIRED] org.eclipse.jetty.websocket#websocket-common;9.2.
15.v20160210!websocket-common.jar
[debug]         [NOT REQUIRED] org.eclipse.jetty.websocket#websocket-api;9.2.15.
v20160210!websocket-api.jar
[debug]         [NOT REQUIRED] org.seleniumhq.selenium#selenium-java;2.48.2!sele
nium-java.jar
[debug]         [NOT REQUIRED] org.seleniumhq.selenium#selenium-chrome-driver;2.
48.2!selenium-chrome-driver.jar
[debug]         [NOT REQUIRED] org.seleniumhq.selenium#selenium-edge-driver;2.48
.2!selenium-edge-driver.jar
[debug]         [NOT REQUIRED] org.seleniumhq.selenium#selenium-htmlunit-driver;
2.48.2!selenium-htmlunit-driver.jar
[debug]         [NOT REQUIRED] org.seleniumhq.selenium#selenium-firefox-driver;2
.48.2!selenium-firefox-driver.jar
[debug]         [NOT REQUIRED] org.seleniumhq.selenium#selenium-ie-driver;2.48.2
!selenium-ie-driver.jar
[debug]         [NOT REQUIRED] org.seleniumhq.selenium#selenium-safari-driver;2.
48.2!selenium-safari-driver.jar
[debug]         [NOT REQUIRED] org.seleniumhq.selenium#selenium-support;2.48.2!s
elenium-support.jar
[debug]         [NOT REQUIRED] org.webbitserver#webbit;0.4.14!webbit.jar
[debug]         [NOT REQUIRED] org.seleniumhq.selenium#selenium-leg-rc;2.48.2!se
lenium-leg-rc.jar
[debug]         [NOT REQUIRED] org.seleniumhq.selenium#selenium-remote-driver;2.
48.2!selenium-remote-driver.jar
[debug]         [NOT REQUIRED] cglib#cglib-nodep;2.1_3!cglib-nodep.jar
[debug]         [NOT REQUIRED] com.google.code.gson#gson;2.3.1!gson.jar
[debug]         [NOT REQUIRED] org.seleniumhq.selenium#selenium-api;2.48.2!selen
ium-api.jar
[debug]         [NOT REQUIRED] org.apache.commons#commons-exec;1.3!commons-exec.
jar
[debug]         [NOT REQUIRED] net.java.dev.jna#jna;4.1.0!jna.jar
[debug]         [NOT REQUIRED] net.java.dev.jna#jna-platform;4.1.0!jna-platform.
jar
[debug]         [NOT REQUIRED] io.netty#netty;3.5.2.Final!netty.jar(bundle)
[debug]         [NOT REQUIRED] org.scalatest#scalatest_2.11;2.2.6!scalatest_2.11
.jar(bundle)
[debug]         [NOT REQUIRED] com.typesafe.play#play-ws_2.11;2.5.0!play-ws_2.11
.jar
[debug]         [NOT REQUIRED] org.scala-lang.modules#scala-xml_2.11;1.0.2!scala
-xml_2.11.jar(bundle)
[debug]         [NOT REQUIRED] org.asynchttpclient#async-http-client;2.0.0-RC9!a
sync-http-client.jar
[debug]         [NOT REQUIRED] oauth.signpost#signpost-core;1.2.1.2!signpost-cor
e.jar
[debug]         [NOT REQUIRED] oauth.signpost#signpost-commonshttp4;1.2.1.2!sign
post-commonshttp4.jar
[debug]         [NOT REQUIRED] org.asynchttpclient#netty-resolver-dns;2.0.0-RC9!
netty-resolver-dns.jar
[debug]         [NOT REQUIRED] org.javassist#javassist;3.20.0-GA!javassist.jar(b
undle)
[debug]         [NOT REQUIRED] org.asynchttpclient#netty-resolver;2.0.0-RC9!nett
y-resolver.jar
[debug]         [NOT REQUIRED] org.asynchttpclient#netty-codec-dns;2.0.0-RC9!net
ty-codec-dns.jar
[debug]         [NOT REQUIRED] com.typesafe.play#play-omnidoc_2.11;2.5.3!play-om
nidoc_2.11.jar
[debug]         [NOT REQUIRED] com.typesafe.play#play-docs_2.11;2.5.3!play-docs_
2.11.jar
[debug]         [NOT REQUIRED] com.typesafe.play#play-doc_2.11;1.2.2!play-doc_2.
11.jar
[debug]         [NOT REQUIRED] org.pegdown#pegdown;1.4.0!pegdown.jar
[debug]         [NOT REQUIRED] org.parboiled#parboiled-java;1.1.5!parboiled-java
.jar(bundle)
[debug]         [NOT REQUIRED] org.parboiled#parboiled-core;1.1.5!parboiled-core
.jar(bundle)
[debug]         [NOT REQUIRED] org.ow2.asm#asm;4.1!asm.jar
[debug]         [NOT REQUIRED] org.ow2.asm#asm-tree;4.1!asm-tree.jar
[debug]         [NOT REQUIRED] org.ow2.asm#asm-analysis;4.1!asm-analysis.jar
[debug]         [NOT REQUIRED] org.ow2.asm#asm-util;4.1!asm-util.jar
[debug]         [NOT REQUIRED] org.scala-lang#scala-compiler;2.11.8!scala-compil
er.jar
[debug]         [NOT REQUIRED] org.scala-lang#scala-reflect;2.11.8!scala-reflect
.jar
[debug]         [NOT REQUIRED] org.scala-lang.modules#scala-xml_2.11;1.0.4!scala
-xml_2.11.jar(bundle)
[debug]         [NOT REQUIRED] jline#jline;2.12.1!jline.jar
[debug] :: resolution report :: resolve 4412ms :: artifacts dl 241ms
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 universal produced in D:\Java workspace\play-elastic-beanstalk\target\resolu
tion-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-universal.
xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 universal-docs produced in D:\Java workspace\play-elastic-beanstalk\target\r
esolution-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-unive
rsal-docs.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 universal-src produced in D:\Java workspace\play-elastic-beanstalk\target\re
solution-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-univer
sal-src.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 compile produced in D:\Java workspace\play-elastic-beanstalk\target\resoluti
on-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-compile.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 runtime produced in D:\Java workspace\play-elastic-beanstalk\target\resoluti
on-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-runtime.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 test produced in D:\Java workspace\play-elastic-beanstalk\target\resolution-
cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-test.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 provided produced in D:\Java workspace\play-elastic-beanstalk\target\resolut
ion-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-provided.xm
l
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 optional produced in D:\Java workspace\play-elastic-beanstalk\target\resolut
ion-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-optional.xm
l
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 docker produced in D:\Java workspace\play-elastic-beanstalk\target\resolutio
n-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-docker.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 windows produced in D:\Java workspace\play-elastic-beanstalk\target\resoluti
on-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-windows.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 linux produced in D:\Java workspace\play-elastic-beanstalk\target\resolution
-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-linux.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 rpm produced in D:\Java workspace\play-elastic-beanstalk\target\resolution-c
ache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-rpm.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 debian produced in D:\Java workspace\play-elastic-beanstalk\target\resolutio
n-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-debian.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 compile-internal produced in D:\Java workspace\play-elastic-beanstalk\target
\resolution-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-com
pile-internal.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 runtime-internal produced in D:\Java workspace\play-elastic-beanstalk\target
\resolution-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-run
time-internal.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 test-internal produced in D:\Java workspace\play-elastic-beanstalk\target\re
solution-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-test-i
nternal.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 plugin produced in D:\Java workspace\play-elastic-beanstalk\target\resolutio
n-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-plugin.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 sources produced in D:\Java workspace\play-elastic-beanstalk\target\resoluti
on-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-sources.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 docs produced in D:\Java workspace\play-elastic-beanstalk\target\resolution-
cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-docs.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 pom produced in D:\Java workspace\play-elastic-beanstalk\target\resolution-c
ache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-pom.xml
[debug]         report for play-elastic-beanstalk#play-elastic-beanstalk_2.11;0.
2.0 scala-tool produced in D:\Java workspace\play-elastic-beanstalk\target\resol
ution-cache\reports\play-elastic-beanstalk-play-elastic-beanstalk_2.11-scala-too
l.xml
[debug]         resolve done (4412ms resolve - 241ms download)
[info] Done updating.
[debug] Uptodate: D:\Java workspace\play-elastic-beanstalk\target\scala-2.11\api

[debug] Jar uptodate: D:\Java workspace\play-elastic-beanstalk\target\scala-2.11
\play-elastic-beanstalk_2.11-0.2.0-javadoc.jar
[debug] [naha]
[debug] [naha] Initial source changes:
[debug] [naha]  removed:Set()
[debug] [naha]  added: Set()
[debug] [naha]  modified: Set()
[debug] [naha] Invalidated products: Set()
[debug] [naha] External API changes: API Changes: Set()
[debug] [naha] Modified binary dependencies: Set()
[debug] [naha] Initial directly invalidated sources: Set()
[debug] [naha]
[debug] [naha] Sources indirectly invalidated by:
[debug] [naha]  product: Set()
[debug] [naha]  binary dep: Set()
[debug] [naha]  external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings:
[debug]         (D:\Java workspace\play-elastic-beanstalk\conf\application.conf,
D:\Java workspace\play-elastic-beanstalk\target\scala-2.11\classes\application.c
onf)
[debug]         (D:\Java workspace\play-elastic-beanstalk\conf\logback.xml,D:\Ja
va workspace\play-elastic-beanstalk\target\scala-2.11\classes\logback.xml)
[debug]         (D:\Java workspace\play-elastic-beanstalk\conf\production.conf,D
:\Java workspace\play-elastic-beanstalk\target\scala-2.11\classes\production.con
f)
[debug]         (D:\Java workspace\play-elastic-beanstalk\conf\routes,D:\Java wo
rkspace\play-elastic-beanstalk\target\scala-2.11\classes\routes)
[debug] Jar uptodate: D:\Java workspace\play-elastic-beanstalk\target\scala-2.11
\play-elastic-beanstalk_2.11-0.2.0-web-assets.jar
[debug] Jar uptodate: D:\Java workspace\play-elastic-beanstalk\target\scala-2.11
\play-elastic-beanstalk_2.11-0.2.0.jar
[debug] Jar uptodate: D:\Java workspace\play-elastic-beanstalk\target\scala-2.11
\play-elastic-beanstalk_2.11-0.2.0-sans-externalized.jar
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.typesafe.sbt.packager.docker.DockerPlugin$.com$typesafe$sbt$packa
ger$docker$DockerPlugin$$makeAdd(DockerPlugin.scala:161)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSetting
s$8.apply(DockerPlugin.scala:88)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSetting
s$8.apply(DockerPlugin.scala:79)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
8)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
8)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
tions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:dockerCommands) java.lang.ArrayIndexOutOfBoundsException: 1
[error] Total time: 9 s, completed Feb 1, 2018 1:59:12 PM
```
i'm using last sbt installation package here :
https://www.scala-sbt.org/download.html

i'm using windows 8.1

**Comment by muuki88** [comment]
Thanks for your bug request :)

Can you provide a minimal `build.sbt` to reproduce this? The [build.sbt](https://github.com/kipsigman/play-elastic-beanstalk/blob/master/build.sbt) seems a bit old.
