### ISSUE TITLE
plugin load failed with Scala 3

### ISSUE THREAD

**Issue by doofin** [sbt/sbt-native-packager#1561]
## Expected behaviour

sbt project load should succeed

## Actual behaviour

sbt project load failed

## Information

- What sbt-native-packager are you using 1.9.16
- What sbt version 1.8
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ) linux
- What package are you building (e.g. docker, rpm, ...)
- What version has your build tool (find out with e.g. `rpm --version`)
- What is your target system (e.g. Ubuntu 16.04, CentOS 7)

```
java.lang.IllegalStateException: Tried to invoke register on closed repostitory sbt.internal.nio.FileTreeRepositoryImpl@b4c4ac4
	at sbt.internal.nio.FileTreeRepositoryImpl.throwIfClosed(FileTreeRepositoryImpl.scala:143)
	at sbt.internal.nio.FileTreeRepositoryImpl.register(FileTreeRepositoryImpl.scala:112)
	at sbt.nio.Settings$.$anonfun$inputPathSettings$3(Settings.scala:157)
	at sbt.nio.Settings$.$anonfun$inputPathSettings$3$adapted(Settings.scala:157)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at sbt.nio.Settings$.$anonfun$inputPathSettings$2(Settings.scala:157)
	at sbt.nio.Settings$.$anonfun$inputPathSettings$2$adapted(Settings.scala:156)
	at scala.Option.foreach(Option.scala:407)
	at sbt.nio.Settings$.$anonfun$inputPathSettings$1(Settings.scala:156)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.IllegalStateException: Tried to invoke register on closed repostitory sbt.internal.nio.FileTreeRepositoryImpl@b4c4ac4
	at sbt.internal.nio.FileTreeRepositoryImpl.throwIfClosed(FileTreeRepositoryImpl.scala:143)
	at sbt.internal.nio.FileTreeRepositoryImpl.register(FileTreeRepositoryImpl.scala:112)
	at sbt.nio.Settings$.$anonfun$inputPathSettings$3(Settings.scala:157)
	at sbt.nio.Settings$.$anonfun$inputPathSettings$3$adapted(Settings.scala:157)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at sbt.nio.Settings$.$anonfun$inputPathSettings$2(Settings.scala:157)
	at sbt.nio.Settings$.$anonfun$inputPathSettings$2$adapted(Settings.scala:156)
	at scala.Option.foreach(Option.scala:407)
	at sbt.nio.Settings$.$anonfun$inputPathSettings$1(Settings.scala:156)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

```

**Comment by mkurz** [comment]
I can't see why this should have anything to do with Scala 3. sbt-native-packager is a sbt plugin, and sbt pugins do use Scala 2.12 (for sbt 1.x).
