### ISSUE TITLE
Build failed on OS X

### ISSUE THREAD

**Issue by awasilyev** [sbt/sbt-native-packager#327]
latest sbt-native-packager. rpmbuild version 5.4.4

```
....
[info] Executing(%install): /bin/sh -e /var/folders/vx/1pvt1gbs0dgdx_h23ltpsrym0000gn/T/sbt_49d26b67/rpm-tmp.2944
[error] + umask 022
[error] + cd /Users/alw/xxx/xxx/core/distribution/target/rpm/BUILD
[error] + /bin/rm -rf /Users/alw/xxx/xxx/core/distribution/target/rpm/buildroot
[error] + /bin/mkdir -p /Users/alw/xxx/xxx/core/distribution/target/rpm/buildroot
[error] + '[' -e /Users/alw/xxx/xxx/core/distribution/target/rpm/buildroot ']'
[error] + mv /Users/alw/xxx/xxx/core/distribution/target/rpm/tmp-buildroot/etc /Users/alw/xxx/xxx/core/distribution/target/rpm/tmp-buildroot/opt /Users/alw/xxx/xxx/core/distribution/target/rpm/tmp-buildroot/var /Users/alw/xxx/xxx/core/distribution/target/rpm/buildroot
[error] + '%{_rpmconfigdir}/brp-compress'
[error] /var/folders/vx/1pvt1gbs0dgdx_h23ltpsrym0000gn/T/sbt_49d26b67/rpm-tmp.2944: line 32: fg: no job control
[error] error: Bad exit status from /var/folders/vx/1pvt1gbs0dgdx_h23ltpsrym0000gn/T/sbt_49d26b67/rpm-tmp.2944 (%install)
[error]     Bad exit status from /var/folders/vx/1pvt1gbs0dgdx_h23ltpsrym0000gn/T/sbt_49d26b67/rpm-tmp.2944 (%install)
[info]
[info]
[info] RPM build errors:
java.lang.RuntimeException: Unable to run rpmbuild, check output for details.
        at scala.sys.package$.error(package.scala:27)
        at com.typesafe.sbt.packager.rpm.RpmHelper$$anonfun$buildPackage$1.apply(RpmHelper.scala:89)
        at com.typesafe.sbt.packager.rpm.RpmHelper$$anonfun$buildPackage$1.apply(RpmHelper.scala:74)
        at sbt.IO$.withTemporaryDirectory(IO.scala:285)
[error] /var/folders/vx/1pvt1gbs0dgdx_h23ltpsrym0000gn/T/sbt_49d26b67/rpm-tmp.2944: line 32: fg: no job control
[error] error: Bad exit status from /var/folders/vx/1pvt1gbs0dgdx_h23ltpsrym0000gn/T/sbt_49d26b67/rpm-tmp.2944 (%install)
[error]     Bad exit status from /var/folders/vx/1pvt1gbs0dgdx_h23ltpsrym0000gn/T/sbt_49d26b67/rpm-tmp.2944 (%install)
[info]
[info]
[info] RPM build errors:
java.lang.RuntimeException: Unable to run rpmbuild, check output for details.
    at scala.sys.package$.error(package.scala:27)
    at com.typesafe.sbt.packager.rpm.RpmHelper$$anonfun$buildPackage$1.apply(RpmHelper.scala:89)
    at com.typesafe.sbt.packager.rpm.RpmHelper$$anonfun$buildPackage$1.apply(RpmHelper.scala:74)
    at sbt.IO$.withTemporaryDirectory(IO.scala:285)
......
```

**Comment by IrfanAnsari** [comment]
@awasilyev @nefilim 
Has anyone come across any solution for the above issue? I am having the same issue as well.

Regards,
Irfan

**Comment by nefilim** [comment]
@IrfanAnsari nope not really, i've opened an issue here: https://github.com/Homebrew/homebrew/issues/35062

there's a patch in there that works apparently, i briefly tried it yesterday but for some reason homebrew didn't pick it up. i haven't looked deeper into it, i've resorted to a linux build server when i encountered this originally so just going with that for now.

**Comment by muuki88** [comment]
Thanks @nefilim for updating :)

**Comment by IrfanAnsari** [comment]
Thanks Guys, much appreciated your reply. I will try the patch at some point and will post about how it goes.

Regards,
Irfan

**Comment by kayvank** [comment]
Thank you, this page solve my problem with native packager.  Here is what I did on my os x el capitan:
brew install rpm
& I added the  rpmBrpJavaRepackJars := true
