### ISSUE TITLE
Created Volumes in Docker plugin, are not owned by daemon.

### ISSUE THREAD

**Issue by kanuku** [sbt/sbt-native-packager#485]
When creating volumes with the Docker plugin, the created volumes are still owned by the `root`, instead of the `deamon` user.

These are the created volumes:
 *  `/data/demo/logs` and `/data/demo/configuration`

```
09:03:55,813 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [/data/demo/logs/application.log]
09:03:55,815 |-ERROR in ch.qos.logback.core.FileAppender[FILE] - openFile(/data/demo/logs/application.log,true) call failed. java.io.FileNotFoundException: /data/demo/logs/application.log (Permission denied)
	at java.io.FileNotFoundException: /data/demo/logs/application.log (Permission denied)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:149)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at play.api.Logger$$anonfun$configure$3.apply(Logger.scala:256)
	at 	at play.api.Logger$$anonfun$configure$3.apply(Logger.scala:256)
	at 	at scala.Option.foreach(Option.scala:245)
	at 	at play.api.Logger$.configure(Logger.scala:256)
	at 	at play.api.Application$class.$init$(Application.scala:272)
	at 	at play.api.DefaultApplication.<init>(Application.scala:406)
	at 	at play.core.StaticApplication.<init>(ApplicationProvider.scala:53)
	at 	at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
	at 	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
	at 	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
	at 	at scala.Option.map(Option.scala:145)
	at 	at play.core.server.NettyServer$.main(NettyServer.scala:275)
	at 	at play.core.server.NettyServer.main(NettyServer.scala)
09:03:55,816 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:03:55,816 |-I
```

You can reproduce this issue with this [demo project](https://github.com/mercados/scala-play-demo):

**Comment by kanuku** [comment]
This is not really an issue as it can be solved by using either a script or the CMD ["chown -R daemon /data && .bin/demo"

**Comment by muuki88** [comment]
Thanks for the report. We will extend the functionality of the docker plugin dramatically in #453 
Adding the `CMD ["chown -R daemon /data && .bin/demo"` will be a lot easier then.

**Comment by muuki88** [comment]
@kanuku , I read some topics on docker volumes. The gist is, that `exportVolumes` are not meant to be 


- [What is the (best) way to manage permissions for docker shared volumes](http://stackoverflow.com/questions/23544282/what-is-the-best-way-to-manage-permissions-for-docker-shared-volumes)
- [Docker Volumes - Managing Data in Containers](https://docs.docker.com/userguide/dockervolumes/)
- [Docker 7198](https://github.com/docker/docker/issues/7198)

**Comment by muuki88** [comment]
First work done in #486
