### ISSUE TITLE
How to force tag in docker sbt native packager?

### ISSUE THREAD

**Issue by AshleyAitken** [sbt/sbt-native-packager#556]
Hi,

When I use the update latest option for SBT docker native plugin I set like this:

dockerUpdateLatest in Docker := true

I get:

[info] Built image private.com/hedventures/a3-write-front:0.1-SNAPSHOT
time="2015-04-18T03:55:39+08:00" level="fatal" msg="Error response from daemon: Conflict: Tag latest is already set to image bdab0b723ec6e7378f6c0add1cbc54cb682d3e7a782d142d65482a829bb304d0, if you want to replace it, please use -f option" 
[trace] Stack trace suppressed: run last a3-write-front/docker:publishLocal for the full output.
[error] (a3-write-front/docker:publishLocal) Failed to run docker tag

I believe there already exists a private.com/hedventures/a3-write-front:0.1-SNAPSHOT with latest tag.  This is a new build of that, i.e. the tagging as latest works the first time (if the images is not already tagged as latest) but fails the second (and subsequent times) publishLocal.

Is it possible to force (-f) the tagging somehow with SBT docker native plugin?

Thanks,
Ashley.

SBT 0.13
SBT Native Package 0.8.0-RC1

That is in response to a docker:publishLocal for a3-write-front.

Full error is:

[info] Built image tutum.co/hedventures/a3-write-front:0.1-SNAPSHOT
java.lang.RuntimeException: Failed to run docker tag
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.sbt.packager.docker.DockerPlugin$class.publishLocalDocker(DockerPlugin.scala:114)
	at com.typesafe.sbt.SbtNativePackager$.publishLocalDocker(PackagerPlugin.scala:10)
	at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$dockerSettings$15.apply(DockerPlugin.scala:195)
	at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$dockerSettings$15.apply(DockerPlugin.scala:194)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:35)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (a3-write-front/docker:publishLocal) Failed to run docker tag

**Comment by AshleyAitken** [comment]
Sorry, I believe SBT is 0.13.1 (well, that's what sbt --version says ;-)

**Comment by muuki88** [comment]
I think we only fixed this for the 1.0.0 branch. Why are you using 0.8.x?

**Comment by muuki88** [comment]
This issue is fixed in `0.8.0`.

**Comment by AshleyAitken** [comment]
Thank you again @muuki88 I will upgrade.  I looked at the docs and didn't see (or understand) how to force the latest option (or is that the default?).  I will see, I guess.

**Comment by yanns** [comment]
I have this error when upgrading from `1.1.5` to `1.2.0`.
I'll check further.

**Comment by muuki88** [comment]
Thanks @yanns 😃😍

**Comment by yanns** [comment]
As documented in http://www.scala-sbt.org/sbt-native-packager/formats/docker.html#publishing-settings, the docker version should be >= 1.10

https://github.com/sbt/sbt-native-packager/issues/871

**Comment by muuki88** [comment]
Thanks for clarifying 😃
