### ISSUE TITLE
show dockerCommands fails on windows OS

### ISSUE THREAD

**Issue by rsemlal** [sbt/sbt-native-packager#573]
Steps to reproduce:
- Create simple sbt project with sbt-native-packager v1.0.0 and `enablePlugins(DockerPlugin)` in its `build.sbt`
- running an sbt REPL on the project, in a windows console
- submitting the sbt command `show dockerCommands`

The command fails with the following stack trace:
```
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.lang.String.split(Unknown Source)
        at java.lang.String.split(Unknown Source)
        at com.typesafe.sbt.packager.docker.DockerPlugin$.com$typesafe$sbt$packager$docker$DockerPlugin$$makeAdd(DockerPlugin.scala:152)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$8.apply(DockerPlugin.scala:79)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$8.apply(DockerPlugin.scala:70)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

The issue seems to come from the method DockerPlugin.makeAdd (In line 152 of DockerPlugin.scala), on the following line:
```val files = dockerBaseDirectory.split(java.io.File.separator)(1)```
Since on windows java.io.File.separator is `\`, and that split method is supposed to take an regular expression as parameter, the call to split fails for non being able to compile the regex.

This error is also raised on doing a `docker:stage` (it was possible to do a docker:stage on windows with sbt-native-packager:0.8)

**Comment by muuki88** [comment]
Thanks for giving a detailed description. This sounds easy to fix, you mind making a pull request?

**Comment by rsemlal** [comment]
Fine, i will submit a pull request as soon as i can

**Comment by ravetdavid** [comment]
Hi, is there a date for this correction ? or a workaround ?
