### ISSUE TITLE
Trying to Deploy the debian package on Ubuntu AMI

### ISSUE THREAD

**Issue by allnash** [sbt/sbt-native-packager#673]
sudo tail -f /var/log/upstart/<app_name>.log

Oops, cannot start the server.
java.io.FileNotFoundException: /usr/share/app_name/RUNNING_PID (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at play.core.server.ProdServerStart$.createPidFile(ProdServerStart.scala:131)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:45)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Oops, cannot start the server.
java.io.FileNotFoundException: /usr/share/app_name/RUNNING_PID (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at play.core.server.ProdServerStart$.createPidFile(ProdServerStart.scala:131)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:45)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)

When I check in terminal 
$id <app_name>
uid=999(app_name) gid=999(app_name) groups=999(app_name)

What is the issue it seems like the ustart script does this at the End
  exec sudo -u <app_name> bin/<app_name>

Am I missing something?

**Comment by Daxten** [comment]
I have a quite similar problem, it seems that play 2.4.3 packaging is not working atm.
it uses sudo -u {appname} ./bin/{appname} in the upstart script (/etc/init/{appname}.conf, but never creates the user {appname} for me, because of that there are permission problems (for me with writing to h2 database file)
delete the -u {appname} part (the app runs as root then) and it is fixed.

I think this is a bug in sbt-native-packager

**Comment by muuki88** [comment]
You have to configure the `pid` file for play. Otherwise play will try to create one in the executing directory, which is `/usr/share/<packageName>` where only root as write access (which is correct).

See [the docs](http://www.scala-sbt.org/sbt-native-packager/topics/play.html) how to configure this. Also mentioned on the [how to deploy#native-packager](https://playframework.com/documentation/2.4.x/Production#The-Native-Packager) docs at the playframework.

**Comment by muuki88** [comment]
@Daxten running your app as root is _never_ a good idea. Your app can basically compromise your complete system.

**Comment by Daxten** [comment]
sure, but that doesn't fix the issue that the user doesn't exist and my app can't write to the database file :)

**Comment by muuki88** [comment]
The `JavaServerAppPackaging` does create the user in the `postinstall` [routine](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/debian/postinst-template#L5-L6). How do you setup/install your AMI/app
