### ISSUE TITLE
Start command too long on some platforms with big classpaths

### ISSUE THREAD

**Issue by jroper** [sbt/sbt-native-packager#72]
UPDATE: For those who have stumbled across this and want to know what the answer is, read here:

http://www.scala-sbt.org/sbt-native-packager/recipes/longclasspath.html

The generated start script is too long on some platforms (Windows) when the classpath is too big.

There are two ways we could go about solving this:
1. Make it a config option as to whether classpath ordering is maintained, when it's set to false, then use JDK wildcard expansion for the classpath.
2. Implement a loader that will load the classpath specification from a text file, and create a new classloader from that.

Original issue raised here: https://github.com/playframework/playframework/issues/2025

**Comment by gstroup** [comment]
I have a large class path, but I don't care about the ordering.  So, I thought I would try option 1 above, but I must be doing something wrong.  I added those two lines to the top of my build.sbt file, and then ran "activator dist".  
```
import com.typesafe.sbt.packager.Keys._
scriptClasspath := Seq("*")
```
But when I unzip the package and try to run the .bat script in the bin directory, I get an error.  Any ideas what I'm doing wrong?  It seems to be looking for a .conf file in the wrong place.  Sorry, I'm new to Play and SBT!

D:\PredixExperienceHandsOn\predix-seed-1.0.0-SNAPSHOT\bin>predix-seed.bat
Play server process ID is 3156
[error] application - Error reading configuration file D:\PredixExperienceHandsOn\predix-seed-1.0.0-SNAPSHOT\bin\conf\app.conf.org.apache.commons.configuration.ConfigurationException: Cannot locate configuratio
n source D:\PredixExperienceHandsOn\predix-seed-1.0.0-SNAPSHOT\bin\conf\app.conf
Oops, cannot start the server.
@6l6mknpab: Cannot load plugin
        at play.api.WithDefaultPlugins$$anonfun$plugins$1$$anonfun$apply$9.apply(Application.scala:148)
        at play.api.WithDefaultPlugins$$anonfun$plugins$1$$anonfun$apply$9.apply(Application.scala:130)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.List.foreach(List.scala:383)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.immutable.List.map(List.scala:286)
        at play.api.WithDefaultPlugins$$anonfun$plugins$1.apply(Application.scala:130)
        at play.api.WithDefaultPlugins$$anonfun$plugins$1.apply(Application.scala:166)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.WithDefaultPlugins$class.plugins(Application.scala:128)
        at play.api.DefaultApplication.plugins$lzycompute(Application.scala:402)
        at play.api.DefaultApplication.plugins(Application.scala:402)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.lang.NullPointerException
        at com.ge.dsv.common.config.ConfigurationManagerImpl.getProperty(ConfigurationManagerImpl.java:133)
        at com.ge.dsv.cache.InfinispanPlugin.enabled(InfinispanPlugin.java:269)
        at play.api.WithDefaultPlugins$$anonfun$plugins$1$$anonfun$apply$9.apply(Application.scala:138)
        ... 24 more

**Comment by muuki88** [comment]
It's not the start script but some custom configuration you made. Read the error

```
Error reading configuration file D:\PredixExperienceHandsOn\predix-seed-1.0.0-SNAPSHOT\bin\conf\app.conf.org.apache.commons.configuration.ConfigurationException: Cannot locate configuration source D:\PredixExperienceHandsOn\predix-seed-1.0.0-SNAPSHOT\bin\conf\app.conf
```

Can you provide a small example project to reproduce this?

**Comment by gstroup** [comment]
Oh, I see what you mean.  I guess the change to build.sbt did work, and now I'm seeing an error from our custom code.  Strange, it works fine on Linux or Mac, not Windows.  It should be looking for \conf\app.conf not \bin\conf\app.conf.  Anyway, it seems to be a problem in our code now.  Thank you.

**Comment by muuki88** [comment]
Hm. Yep, that's weird. If you find a solution to this, please let us know. Really awkward.

**Comment by ejain** [comment]
Just tried setting `scriptClasspath := Seq("*")`, but then I get `Bad application path: -Dhttp.port=9000`...

**Comment by muuki88** [comment]
which version are you using? There has been a long thread on this on the play github issue list.

You could try the `ClasspathJar` autoplugin. However I didn't try it with play.

**Comment by ejain** [comment]
This is with Play 2.3.8 (and whatever version of the sbt-native-packager it uses).

**Comment by krns** [comment]
@ejain have you solved the problem? Please let me know, I'am facing the same problem...

**Comment by muuki88** [comment]
With the `1.x` branch we provide a handful of solutions. See [docs](http://www.scala-sbt.org/sbt-native-packager/topics/longclasspath.html) for more details. However this currently integrates only with the play `2.4.x` stream smoothly due to the autoplugin migration.

**Comment by gpgekko** [comment]
Did anyone figure out the 'bin/conf' thing? I have the same problem:

> org.apache.commons.vfs2.FileNotFoundException: Could not read from "file:///C:/Users/user/Desktop/application-0.0.1-SNAPSHOT/bin/conf/some.file" because it is a not a file.

**Comment by Kamaraju333** [comment]
when i try to go with the below path 
scriptClasspath := {
  import com.typesafe.sbt.SbtNativePackager._
  import com.typesafe.sbt.packager.Keys._
  import com.typesafe.sbt.packager.archetypes.JavaAppPackaging._
  val classpath = (scriptClasspathOrdering map makeRelativeClasspathNames).value
  val manifest = new java.util.jar.Manifest()
  manifest.getMainAttributes().putValue("Class-Path", classpath.mkString(" "))
  val classpathJar = (target in Universal).value / "lib" / "classpath.jar"
  IO.jar(Seq.empty, classpathJar, manifest)
  Seq("classpath.jar")
}

and run "activator start" i see error
Error: Could not find or load main class play.core.server.NettyServer

**Comment by Kamaraju333** [comment]
Error: Could not find or load main class play.core.server.NettyServer
I am using ScriptClasspath , classpath jar 
as below 
scriptClasspath := {
  import com.typesafe.sbt.SbtNativePackager._
  import com.typesafe.sbt.packager.Keys._
  import com.typesafe.sbt.packager.archetypes.JavaAppPackaging._
  val classpath = (scriptClasspathOrdering map makeRelativeClasspathNames).value
  val manifest = new java.util.jar.Manifest()
  manifest.getMainAttributes().putValue("Class-Path", classpath.mkString(" "))
  val classpathJar = (target in Universal).value / "lib" / "classpath.jar"
  IO.jar(Seq.empty, classpathJar, manifest)
  Seq("classpath.jar")
}
