### ISSUE TITLE
sbt docker:publishLocal fails on Windows 

### ISSUE THREAD

**Issue by mkotsbak** [sbt/sbt-native-packager#760]
Running "sbt docker:publishLocal" fails with this stack trace on Windows (works fine on Linux):

```scala
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.lang.String.split(Unknown Source)
        at java.lang.String.split(Unknown Source)
        at com.typesafe.sbt.packager.docker.DockerPlugin$.com$typesafe$sbt$packager$docker$DockerPlugin$$makeAdd(DockerPlugin.scala:152)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$8.apply(DockerPlugin.scala:79)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$8.apply(DockerPlugin.scala:70)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (*:dockerCommands) java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
```

I guess it is related to the Windows directory separator "\".

**Comment by muuki88** [comment]
Probably. Are you using the spotify docker client?

**Comment by mkotsbak** [comment]
This seems unrelated to Docker client, it happens during build, probably while calculating a cmd path.

**Comment by mkotsbak** [comment]
But Docker toolbox, not spotify.

**Comment by mkotsbak** [comment]
I think we have it here:

```
  /**
   * The separator for makeAdd force UNIX separator.
   * The separator doesn't depend to OS where i build Dockerfile.
   */
  val UnixSeparatorChar = '/'
```
at https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L64

**Comment by raam86** [comment]
Hi I am on 1.2.0-M2 and this issue still isn't fixed. Looks like the code was changed but I am getting array index out of bound error on line 88 (makeAdd). Any help would be greatly appreciated

**Comment by muuki88** [comment]
Damn. Windows is real unforgiving :(
Seems that `dockerBaseDirectory` cannot be split up correctly. Do you have time and patience to debug this further with the `test-project-docker`? If yes, I can give you some hints (my windows machine doesn't work anymore :/ )

**Comment by raam86** [comment]
Yes I would love to do it. 
Please provide as many hints as possible so we can fix it for my windows wielding colleagues :)

**Comment by muuki88** [comment]
Awesome :+1: 

So, first of all `println` debugging is for sbt the technique I currently use to debug (I feel ashamed and should be).

Fixing this bug should only require touching the `DockerPlugin.scala`. Nothing else. You can start the `test-project-docker` by firing up `sbt` in the `test-project-directory`.

The workflow from there on is

1. Change something in your `DockerPlugin.scala`
2. `; r ; docker:publishLocal` in the test-project-docker
3. see if it worked or not. Start with step 1

You can change the `test-project-docker` until you are able to reproduce the error. However don't stage these changes for the real fix then.

**Comment by oporkka** [comment]
I'm also getting errors from running `sbt docker:stage`.

What seems to have happened is that https://github.com/sbt/sbt-native-packager/commit/f52167977e74187a284f5b8392e3bdb64c05b4b6 has been reverted by https://github.com/sbt/sbt-native-packager/commit/101311e4f967cc0117e05358960097b5915b2b38 in 1.1.1

**Comment by mkotsbak** [comment]
Yes, but the last commit was supposed to fix this issue.

**Comment by oporkka** [comment]
It brought the issue of #573 back. Maybe there's something else wrong in the logic.

**Comment by oporkka** [comment]
@mkotsbak I'm wondering that if anyway Unix separator `/` was used for splitting before your commit, how could there actually be a problem with `\` at all? Might there have been actually an old version of `sbt-native-packager` in use? Note that f521679 for #573 that you kind of reverted, fixed the exactly same stack trace (supposedly).

**Comment by mkotsbak** [comment]
@oporkka Yes, I think you might be right, that this issue was really a duplicate of #573, which was not released.

**Comment by mkotsbak** [comment]
Then my commit should be reverted.

**Comment by oporkka** [comment]
I already provided revert (#823 issue, #824 pull request)

**Comment by raam86** [comment]
So whats the decision? Should I do it or is it already fixed?

**Comment by oporkka** [comment]
It has been fixed to master. There's now #842 open for 1.1.x too
