### ISSUE TITLE
docker:publishLocal does not override latest tag

### ISSUE THREAD

**Issue by SharkyLV** [sbt/sbt-native-packager#857]
It appears this is an issue introduced in `1.1.3`

With `dockerUpdateLatest := true` 
in version < `1.1.3` docker:publishLocal succeeds
in version >= `1.1.3` docker:publishLocal fails

```
Error response from daemon: Conflict: Tag X:latest is already set to image 9b68a9e4e758, if you want to replace it, please use -f option
java.lang.RuntimeException: Failed to run docker tag
    at scala.sys.package$.error(package.scala:27)
    at com.typesafe.sbt.packager.docker.DockerPlugin$.publishLocalDocker(DockerPlugin.scala:305)
    at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$14.apply(DockerPlugin.scala:109)
    at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$14.apply(DockerPlugin.scala:108)
    at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
    at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by NeQuissimus** [comment]
@SharkyLV I don't have this issue. I believe this is related to older Docker versions requiring `--force` on tagging operations if a tag already exists. In Docker >= 1.12 this behaviour has been replaced and the `--force` flag deprecated. I don't think this is an issue with `sbt-native-packager`.

**Comment by muuki88** [comment]
Thanks @NeQuissimus for looking into that.

It's quite possible that this is a error correlates with the docker change you mention. Docker is quite cumbersome to maintain as it introduces breaking changes way to often and much as you may expect. 

Thanks to the community keeping up with the changes 😃
